### ISSUE TITLE
[feature] add skybox monoid

### ISSUE THREAD

**Issue by thomasrudin** [minetest-mods/player_monoids#3]
maybe even parts of the skybox def: clouds, textures, type

**Comment by raymoo** [comment]
I'm not particularly active in Minetest anymore, but what would you imagine the monoid operation for skyboxes doing? What would be the valid values for the monoid?

**Comment by thomasrudin** [comment]
Yeah, maybe that would not work like i wanted (switching skyboxes dependent on area/height)
Closing this, as the current solution works just fine: https://github.com/pandorabox-io/skybox
(sorry for pinging you :smile:)
